### ISSUE TITLE
STL files?

### ISSUE THREAD

**Issue by CumpsD** [Telraam/camera-mount#1]
Any chance you can provide an STL file as well please?

I'd like to print this with a MK3S.

**Comment by CumpsD** [comment]
Tried it with an online convert and added them to a M3F file with correct orientation.

In the zip:
* Telraam Housing.3mf
* 529P001-PCB housing-RevA.stl
* 529P002-Window sticker-RevA.stl

[Telraam Housing.zip](https://github.com/Telraam/camera-mount/files/7460929/Telraam.Housing.zip)

Not printed yet!

**Comment by dave-driesmans** [comment]
Thanks David, added it to the repo!
